Repository milieuinfo/webcomponent-vl-ui-tooltip, pull requests merged in 2019-09, with the labels that each got.

#21 UIG-218
  vl-tooltip.src.js
Labels: maintenance

#22 Update link naar demo
  vl-tooltip.src.js
Labels: maintenance

#23 Automatic commit via update script
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/task.md
  package-lock.json
  package.json
Labels: maintenance

#11 Update dependency tooltip.js to v1.3.2
  package-lock.json
  package.json
Labels: dependencies, renovate

#10 Update dependency replace to v1.1.0
  package-lock.json
  package.json
Labels: dependencies, renovate

#9 Update dependency np to v3.1.0
  package-lock.json
  package.json
Labels: dependencies, renovate

#26 Update dependency vl-ui-core to v1.4.6
  package-lock.json
  package.json
Labels: dependencies

#25 Update dependency vl-ui-button to v1.1.9
  package-lock.json
  package.json
Labels: dependencies

#24 Update dependency replace to v1.1.1
  package-lock.json
  package.json
Labels: dependencies

#27 Update dependency vl-ui-core to v1.4.7
  package-lock.json
  package.json
Labels: dependencies

#28 Update dependency vl-ui-button to v1.1.10
  package-lock.json
  package.json
Labels: dependencies

#29 Automatic commit via update script
  demo/demo.css
  package-lock.json
  style.css
Labels: maintenance

#31 UIG-143 - Update bamboo template
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/task.md
  CODEOWNERS
  bamboo-specs/bamboo.yml
  demo/demo.css
  package-lock.json
  package.json
  style.css
Labels: maintenance
