Repository milieuinfo/webcomponent-vl-ui-tooltip, pull requests merged in 2020-02, with the labels that each got.

#56 Stijl import vervangen door inhoud, probleem met absolute paden
  package-lock.json
  package.json
  src/vl-tooltip.src.js
Labels: bug

#57 E2E test verbeteringen
  .gitignore
  demo/vl-tooltip.html
  package-lock.json
  package.json
  test/e2e/components/vl-tooltip.js
  test/e2e/pages/vl-tooltip.page.js
  test/e2e/tooltip.test.js
Labels: bugfix

#58 Gebruik nieuwe hover functie die de MoveTargetOutOfBoundsError verhelpt
  package-lock.json
  test/docker-compose.yml
  test/e2e/tooltip.test.js
Labels: chore

#60 Nieuwe structuur en build scripts implementatie vervangen door vl-ui-core build implementatie
  CODEOWNERS
  bamboo-specs/bamboo.yml
  demo/vl-tooltip.html
  docker-compose-release.yml
  package-lock.json
  package.json
  src/index.js
  src/style.css
  src/vl-tooltip.js
  src/vl-tooltip.src.js
  test/e2e/tooltip.test.js
  test/unit/vl-tooltip.test.html
  vl-tooltip.min.js
  vl-tooltip.src.js
Labels: chore

#59 E2E test verbeteringen
  package-lock.json
  test/docker-compose.yml
  test/e2e/components/vl-tooltip.js
  test/e2e/pages/vl-tooltip.page.js
  test/e2e/tooltip.test.js
Labels: chore

#61 Upgrade vl-ui-button 4.0.0
  README.md
  demo/vl-tooltip.html
  package-lock.json
  package.json
  test/docker-compose.yml
Labels: chore
