Repository milieuinfo/webcomponent-vl-ui-tooltip, pull requests merged in 2020-03, with the labels that each got.

#62 E2E test verbetering is displayed implementatie
  test/e2e/components/vl-tooltip.js
  test/e2e/tooltip.test.js
Labels: chore

#63 Verbetering van falende e2e testen in Firefox
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/task.md
  package-lock.json
  package.json
  test/e2e/components/vl-tooltip.js
  test/e2e/pages/vl-tooltip.page.js
  test/e2e/tooltip.test.js
Labels: chore

#64 Update vl-ui-util
  package-lock.json
  package.json
Labels: chore, maintenance

#65 Update vl-ui-core
  package-lock.json
  package.json
Labels: chore

#66 Update vl-ui-core
  package-lock.json
  package.json
Labels: chore

#73 Tooltip verbergen bij blur in combinatie met shadow DOM parent
  demo/vl-tooltip-test.js
  demo/vl-tooltip.html
  lib/tooltip.js
  package-lock.json
  package.json
  src/vl-tooltip.js
  test/e2e/components/vl-tooltip.js
  test/e2e/pages/vl-tooltip.page.js
  test/e2e/tooltip.test.js
Labels: bug
