Repository milieuinfo/webcomponent-vl-ui-tooltip, pull requests merged in 2020-01, with the labels that each got.

#47 Update vl-ui-util
  bamboo-specs/bamboo.yml
  demo/demo.css
  demo/demo.js
  package-lock.json
  package.json
  style.css
  test/docker-compose.yml
  wct.docker.conf.json
  wct.local.conf.json
Labels: maintenance

#48 E2E opzet
  .gitignore
  .mocharc.js
  demo/demo.css
  index.js
  package-lock.json
  package.json
  test/e2e/components/vl-tooltip.js
  test/e2e/pages/vl-tooltip.page.js
  test/e2e/tooltip.test.js
  test/unit/vl-tooltip.test.html
  test/wct.docker.conf.json
Labels: bugfix

#50 Verwijder pretest fase (installeren chromedriver). Deze komt via vl-ui-util binnen
  package.json
Labels: chore

#51 Update vl-ui-util
  bamboo-specs/bamboo.yml
  package-lock.json
  package.json
  test/docker-compose.yml
Labels: maintenance

#52 Update vl-ui-util
  bamboo-specs/bamboo.yml
  docker-compose-release.yml
  package-lock.json
  package.json
  src/style.scss
  src/vl-tooltip.src.js
Labels: maintenance
